### ISSUE TITLE
What does each parameter mean in raw data?

### ISSUE THREAD

**Issue by XiaRongjie** [shahroudy/NTURGB-D#11]
I appreciate your work very much. There are some questions that plague me.
In raw data and the "read_skeleton_file.m", there are some parameter that I can't really understand what they really mean. As follows:    
body.clipedEdges
body.handLeftConfidence
body.handLeftState
body.handRightConfidence
body.handRightState
body.isResticted
body.leanX
body.leanY
joint.orientationW
joint.orientationX
joint.orientationY
joint.orientationZ
What does each parameter mean? And how can we get these parameter by sensor?
Look forward to your reply!!!

**Comment by lxy5513** [comment]
```
            % 3D location of the joint j
            joint.x = jointinfo(1);
            joint.y = jointinfo(2);
            joint.z = jointinfo(3);
            
            % 2D location of the joint j in corresponding depth/IR frame
            joint.depthX = jointinfo(4);
            joint.depthY = jointinfo(5);
            
            % 2D location of the joint j in corresponding RGB frame
            joint.colorX = jointinfo(6);
            joint.colorY = jointinfo(7);
            
            % The orientation of the joint j
            joint.orientationW = jointinfo(8);
            joint.orientationX = jointinfo(9);
            joint.orientationY = jointinfo(10);
            joint.orientationZ = jointinfo(11); 
            
            %Track body
            joint.trackingState = jointinfo(12)
```

**Comment by shahroudy** [comment]
In almost all of the applications, the 3D locations of the joints are enough...
We tried to keep everything generated by the SDK, so we recorded all.
For more info about the meaning of those extra values, you can read this: 
https://medium.com/@lisajamhoury/understanding-kinect-v2-joints-and-coordinate-system-4f4b90b9df16

**Comment by XiaRongjie** [comment]
> In almost all of the applications, the 3D locations of the joints are enough...
> We tried to keep everything generated by the SDK, so we recorded all.
> For more info about the meaning of those extra values, you can read this:
> https://medium.com/@lisajamhoury/understanding-kinect-v2-joints-and-coordinate-system-4f4b90b9df16

**Comment by XiaRongjie** [comment]
> In almost all of the applications, the 3D locations of the joints are enough...
> We tried to keep everything generated by the SDK, so we recorded all.
> For more info about the meaning of those extra values, you can read this:
> https://medium.com/@lisajamhoury/understanding-kinect-v2-joints-and-coordinate-system-4f4b90b9df16

**Comment by XiaRongjie** [comment]
Thanks for your reply.
With best regard !




------------------ 原始邮件 ------------------
发件人: "Amir Shahroudy"<notifications@github.com>; 
发送时间: 2019年6月6日(星期四) 晚上8:17
收件人: "shahroudy/NTURGB-D"<NTURGB-D@noreply.github.com>; 
抄送: "美美"<1048063959@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shahroudy/NTURGB-D] What does each parameter mean in raw data?(#11)




In almost all of the applications, the 3D locations of the joints are enough...
 We tried to keep everything generated by the SDK, so we recorded all.
 For more info about the meaning of those extra values, you can read this:
 https://medium.com/@lisajamhoury/understanding-kinect-v2-joints-and-coordinate-system-4f4b90b9df16
