### ISSUE TITLE
masked depth and RGB

### ISSUE THREAD

**Issue by Ravi-Garg** [shahroudy/NTURGB-D#12]
I have seen similar quarries but would try to be more specific. 
I want to align the RGB and depth image for the purposes of  RGBD training.

Form the first look it seems that the depth image correspond to a rectangular region in the image which seems consistent for the entire setup. i.e. the RGB image can be simply cropped (and resized) to generate the image for which the depth is shared.

Can you provide with the parameters of such crop?
 If we know the RGB to depth correspondence. The dataset is very useful for testing depth fusion single view reconstruction and tracking etc.

I understand that sharing the depth maps for full image is not memory efficient but the authors could crop the images instead to align with depth-maps and share a even smaller dataset.

R

**Comment by shahroudy** [comment]
One applicable solution for this dataset is to use the skeletal data.
For each video sample, the skeletal data includes a big number of body joints and their precise locations in both RGB and depth frames.
So for each sample you have a big number of mappings.
Keep in mind that the cameras were fixed during each setup (Sxxx in the file names mean this sample is from setup xxx).
So for each camera at each setup you have a huge number of mappings between RGB and depth cameras (and also between the three sensors!).
Finding a transformation between the cameras will be as easy as solving a linear system with a lot of known mappings!
