### ISSUE TITLE
About skeleton orientation data

### ISSUE THREAD

**Issue by milkcat0904** [shahroudy/NTURGB-D#14]
hello, i got a problem when i use the 4 orientations (orientationW, orentationX, orientationY, orientationZ) in the skeleton data. I want to calculate the Euler rotation of each joint. 

So, i think those 4 orientations are every joint quaternions, am I right?
or this 4 orientations are relative quaternion between current joint and last joint?

**Comment by lxy5513** [comment]
I am also confuse about the 4 orientations  usage.

**Comment by shahroudy** [comment]
In almost all of the applications, the 3D locations of the joints are enough...
We tried to keep everything generated by the SDK, so we recorded all.
For more info about the meaning of those extra values, you can read this:
https://medium.com/@lisajamhoury/understanding-kinect-v2-joints-and-coordinate-system-4f4b90b9df16
