### ISSUE TITLE
question about skeleton data

### ISSUE THREAD

**Issue by techjjun** [shahroudy/NTURGB-D#18]
Hi, I'm interested in human action recognition using skeleton data.
When I look in to a data I see some misleading joint parts due to side view of camera.
Like the image below right hand is occluded but kinect camera estimates a women drinking water with two hands.
So i'm curious if it is okay with this kind of misleading joints data as a input to LSTM model.

![image](https://user-images.githubusercontent.com/37102770/46270181-28c12600-c581-11e8-9ca0-1d1374388a14.png)

**Comment by shujah-islam** [comment]
Respected techjjun,
 I am working in Human action recognition. I am unable to plot joints on RGB or depth image. Kindly help me to solve this issue for NTU, SBU Kinect interaction datasets

**Comment by shahroudy** [comment]
What is provided in this dataset are what the Kinect v2 tracker generates.
When some parts of the body are occluded, the calculated 3D location of the body joints will be less accurate.
The studies on this dataset shows a properly trained RNN or LSTM can tackle with the natural noise and inaccuracy of the skeletal data for the task of action recognition.
If your specific requires more accurate joint locations, you can use the triplets of samples captured at the same time from different views to achieve a more accurate 3D pose representation.
