### ISSUE TITLE
Base-line code

### ISSUE THREAD

**Issue by Seanny123** [shahroudy/NTURGB-D#2]
Hey Amir, are there any plans to upload the code used to get the baseline or the state-of-the-art results from either "NTU RGB+D: A Large Scale Dataset for 3D Human Activity Analysis" or "Spatio-Temporal LSTM with Trust Gates for 3D Human Action Recognition"?

**Comment by ljchangyu** [comment]
The baseline code is available at https://github.com/ljchangyu/Spatio-Temporal-LSTM

**Comment by ljchangyu** [comment]
The baseline code of [Spatio-Temporal LSTM with Trust Gates for 3D Human Action Recognition](https://github.com/ljchangyu/Spatio-Temporal-LSTM) is now available at https://github.com/ljchangyu/Spatio-Temporal-LSTM

**Comment by shahroudy** [comment]
Hi @Seanny123, unfortunately the original codes of this work are not going to be released.
But there are some re-implementations of them shared by others.
You can find them on GitHub and other similar repositories.
