### ISSUE TITLE
Need help in plotting joints on RGB on Depth image

### ISSUE THREAD

**Issue by shujah-islam** [shahroudy/NTURGB-D#20]
Hi Respected community of GitHub, 
I am a research student working on Human action recognition and need help in: 

- Plotting joints point on RGB and Depth frames (pictures)
- Making skeleton using joints on RGB and Depth frames (pictures)
I have used show_skeleton_on_depthmaps.m & show_skeleton_on_RGB_frames.m but unable to understand how to watch output in term of picture or video ( joints on RGB and Depth frames) or not understand how to use "### outputvideofilename"

**Comment by shahroudy** [comment]
The provided MATLAB code is only a sample to show how one can read skeleton data and find its corresponding pixels in RGB and depth frames.
You may need to do some extra coding to get what you are looking for in your favorite programming environment.
