### ISSUE TITLE
negative joint coordinates 

### ISSUE THREAD

**Issue by thekoshkina** [shahroudy/NTURGB-D#22]
Some of the joint coordinates are negative. Can you please explain how these coordinates were calculated/ normalized? 

I want to use my data on a model pre trained with NTURGB-D, so i need to get it in the same format

**Comment by shahroudy** [comment]
The recorded joint values are what the Kinect SDK's tracker generates.
They are calculated based on the camera's coordinate system.
Please look here for more info:
https://medium.com/@lisajamhoury/understanding-kinect-v2-joints-and-coordinate-system-4f4b90b9df16
