### ISSUE TITLE
Is there any way i can download only the skeleton data 

### ISSUE THREAD

**Issue by NanYoMy** [shahroudy/NTURGB-D#23]
hi, i really appreciate your work, but i wonder to know, Is there any way i can download the skeleton data only ?

**Comment by ljchangyu** [comment]
Yes. The package of the skeleton data can be downloaded from the dataset website.

**Comment by shahroudy** [comment]
Yes, in the dataset's website, the skeletal data, the depthmpas, the masked depthmaps, the RGB videos and the IR videos are provided as separated files and you can download whatever you are interested in.
