### ISSUE TITLE
“FloorClipPlane” data

### ISSUE THREAD

**Issue by handsomeyang** [shahroudy/NTURGB-D#28]
Hi, could you provide “FloorClipPlane” data for each camera in each setup so that we can transform body joints from camera coordinates to world coordinates? Thanks.

**Comment by shahroudy** [comment]
Hi, unfortunately no "FloorClipPlan" data has been recorded.
You can try fitting a 3D plane in the depthmaps and define a world coordinates.
By the way, more common alternative solution is to define a body coordinate system instead.
More details about this "normalization pre-processing step" is provided in the [CVPR paper](https://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Shahroudy_NTU_RGBD_A_CVPR_2016_paper.pdf), section 5.1.
