### ISSUE TITLE
Intrinsic parameters of Kinect

### ISSUE THREAD

**Issue by kemangjaka** [shahroudy/NTURGB-D#29]
Hi, thank you for providing awesome dataset!
I want to re-project the depth image to the 3D point cloud. 
How do I get the information of intrinsic parameters of each Kinect?

Thanks in advance for considering!

**Comment by hosamyousof** [comment]
@ryohachiuma  How did you get the Intrinsic parameters of Kinect V2 camera

I want the following values 
{
        'id': '',
        'center': [],
        'focal_length': [],
        'radial_distortion': [],
        'tangential_distortion': [],
        'res_w': 0,
        'res_h': 0,
        'azimuth': 0,  # Only used for visualization
    }

**Comment by erinchen824** [comment]
> Hi, thank you for providing awesome dataset! I want to re-project the depth image to the 3D point cloud. How do I get the information of intrinsic parameters of each Kinect?
> 
> Thanks in advance for considering!

Hi, did you find the  intrinsic parameters? Thanks!

**Comment by SaiGP** [comment]
@hosamyousof / @erinchen824  have you done the conversion to Point Cloud? can you point me to the code?
