### ISSUE TITLE
Error in Estimated Skeleton Data

### ISSUE THREAD

**Issue by sksenthilkumar** [shahroudy/NTURGB-D#31]
Sample: "S001C001P001R001A027"
Action: Jump Up

In the RGB video, there exists one person performing the action. But there exist joint values of two persons in the skeleton data (the file named: S001C001P001R001A027.skeleton). This is the case for a few other samples also like S001C001P001R001A028, S001C001P001R001A024, S001C001P001R001A026, S001C001P001R001A029. 

P.S These are the cases that I found so far in examining the data. 

Is this an error? If yes, anyways to eliminate this?

**Comment by shahroudy** [comment]
Hi and thank you for asking about this.
Yes, sometimes the Kinect's SDK detects wrong human bodies on objects like chairs, tables, etc.
Almost all the time you can find which skeleton to work on by considering which one moves more, as mentioned in FAQs:
_**How did you choose the main actor in the preprocessing step?**
We used a heuristic method. It's very simple (but not necessarily correct for all the samples). We consider the variance of the X, Y, and Z values of all the joints and add them up. We took the body with the higher value as the main subject._

**Comment by sksenthilkumar** [comment]
Thanks for your reply. Will try to clean the data based on your suggestion. Apart from the above-mentioned error, I also found other errors in the two-person activities such as 'walking apart', 'walking towards', the skeleton data of the second person is missing in all the frames or at least in few frames. example cases: 'S001C001P003R001A059', 'S001C001P003R001A060', 'S006C002P015R002A060', 'S008C001P007R001A060'.  

Is there any way to clean such data? Thanks in advance.

**Comment by shahroudy** [comment]
No, we consider these as naturally existing errors in the data captured by Kinect sensor.

**Comment by sksenthilkumar** [comment]
Thanks!
