### ISSUE TITLE
how multiple persons are handled In P-LSTM

### ISSUE THREAD

**Issue by sksenthilkumar** [shahroudy/NTURGB-D#32]
In the referred paper "NTU RGB+D: A Large Scale Dataset for 3D Human Activity Analysis", A base model called P-LSTM has been proposed. How does the proposed model handle the data when there are two persons present in a single frame? 

I couldn't find this information in the paper.

Thanks in advance.

**Comment by junliu021** [comment]
1 You could treat each skeleton separately, and then fuse the results of them
2 You could use a hierarchical structured network to handle it.
