### ISSUE TITLE
Question about 3D skeletion data?

### ISSUE THREAD

**Issue by qiuqicao77** [shahroudy/NTURGB-D#33]
Hello, i got a question about the relation between 3D joints data and color_x, color_y, since i want to use the inference result from simple baseline which only has the color_x, color_y to replace ground truth NTU 3D joints. However, i don't know how to transfer color_x, color_y to joint.x joint.y.

**Comment by shahroudy** [comment]
Hi, this is more-or-less the same as aligning problem across RGB and depth frames.
Please look at Q2 in FAQs:

Q2: I want to align RGB and depth frames. Are there any camera calibration data recorded?
A2: Unfortunately no camera calibration info is recorded. However, one applicable solution for this is to use the skeletal data. For each video sample, the skeletal data includes a big number of body joints and their precise locations in both RGB and depth frames. So for each sample you have a big number of mappings. Keep in mind that the cameras were fixed during each setup (Sxxx in the file names mean this sample is from setup xxx). So for each camera at each setup you have a huge number of mappings between RGB and depth cameras (and also between the three sensors!). Finding a transformation between the cameras will be as easy as solving a linear system with a lot of known points!
