### ISSUE TITLE
how to ensure the accuracy of the keypoints

### ISSUE THREAD

**Issue by jet-yangqs** [shahroudy/NTURGB-D#34]
Thank you for your great work on these two data sets. Here is a question that how do you ensure the accuracy of 25 key points? Does the player need to wear some markers to play the action? If possible, could you please share some details of capturing the dataset or a simple walkthrough introducing how to use kinects V2 to capture data the same as NTU RGB+D.

**Comment by ljchangyu** [comment]
Hi yangqs, the key-points are provided by Kinect with its pose tracking algorithm (no requirements of any markers). Thus they may be inaccurate sometimes.
