### ISSUE TITLE
Ask some details about NTU-RGBD dataset

### ISSUE THREAD

**Issue by HenryDo147** [shahroudy/NTURGB-D#36]
Hello, I'm a graduate student collecting a dataset about skeleton and pose estimation. I want to label the  true 3d joint position in the world coordinate. I want to know what is the method that your team label the 3d joint position. did your team use Kinect SDK? thanks.

**Comment by shahroudy** [comment]
Hi,
Yes as mentioned in the paper, we collected this dataset using Microsoft Kinect.
