### ISSUE TITLE
Question regarding action span

### ISSUE THREAD

**Issue by usamahjundia** [shahroudy/NTURGB-D#41]
Is there any information at all on when the action begin and ends? Or have anyone came up with a heuristics to determine which parts of the clip contains the action?

I am asking this because from what i observed, in most clips i see that the action does not immediately begin, but rather, about 1/3 to 1/2 into the clip (these numbers came from like 10 clips, i cannot say anything about the significance). Having the idle frames counted towards the action might add noise to the data..

Does the dataset provide any info regarding at what time the action happened, or do i need to resort to heuristics along the lines of what i mentioned above?

**Comment by Anirudh257** [comment]
@usamahjundia I am not sure whether it answers your question but when I made the data from https://github.com/microsoft/View-Adaptive-Neural-Networks-for-Skeleton-based-Human-Action-Recognition, the data generated contained the exact timesteps at which the action starts, when the action ends, number of the frames in a particular action.

**Comment by usamahjundia** [comment]
Thanks for the answer, @Anirudh257 , in the end, for each video i decided to just skip x frames where x is a certain percentage of the total frames of every video. so far, this heuristics works pretty well. Seems like the repo you mentioned implements better heuristics, which is a helpful info. Cheers and thanks again!
