### ISSUE TITLE
Can I get the original IR maps

### ISSUE THREAD

**Issue by Cxiada** [shahroudy/NTURGB-D#51]
Hi,
Great datasets！It helped me a lot。
but ，my research direction now is to detect key points based on IR images and depth maps ，Can you provide the original 16 bit IR maps？

**Comment by shahroudy** [comment]
Hi, thank you for your interest in our work.
All the provided depthmaps and IR images (.png files) are the original images we received from Kinect.
Do you see any .png files in your folders (for example in S001C001P001R001A001)?
