### ISSUE TITLE
How are different backgrounds in the dataset distributed in the dataset?

### ISSUE THREAD

**Issue by yuehniu** [shahroudy/NTURGB-D#55]
In the TPAMI paper "NTU RGB+D 120", it says the dataset has various environmental conditions, with 32 collection setups and 96 different backgrounds. Can you explain more how are different backgrounds distributed in the dataset? For example, does each collection setup has 3 different backgrounds? Or there is no specific connections between the collection setup and backgrounds?

**Comment by junliu021** [comment]
Thanks for your question. in each setup, we have 3 cameras, thus, we have 32*3 sets of backgrounds.
