### ISSUE TITLE
Can't finish download request form

### ISSUE THREAD

**Issue by danilobcardoso** [shahroudy/NTURGB-D#56]
Hi;

    I'm trying to apply for NTU120 dataset download authorization, but the system fails to complete the operation. It seems that a database error occurs (please see image below). Is there any other form to request access? 

![image](https://user-images.githubusercontent.com/2613880/122977479-d8f79e00-d36b-11eb-8391-217647c13788.png)

 Cheers.

**Comment by dragen1860** [comment]
+1, same problem came acrossed. any succeed to download the RGB raw video, could you kindly share a private link to my gmail:

liangqu.long@gmail.com  Thank you very much.

**Comment by zhengthomastang** [comment]
+1 In need of the dataset (zhtang@uw.edu)

**Comment by Csmwax** [comment]
Hi all, the dataset server is undergoing an update, and will recover very soon. Thank you.

**Comment by yanghhx** [comment]
+1 I badly need the skeleton data of NTU 120 for my experiment. Could you kindly share a private link to my gmail:

qinyangz@163.com Thank you very much.

**Comment by hosamyousof** [comment]
You can use the new link to make new request 

https://rose1.ntu.edu.sg/dataset/actionRecognition/
