### ISSUE TITLE
About the body tracking ID 

### ISSUE THREAD

**Issue by dracarys983** [shahroudy/NTURGB-D#6]
Hello, I have a confusion about the tracking ID of the skeleton.
For a subject in a video, is the tracking ID of that subject's skeleton constant for the entire video?

For e.g: In the file S010C003P025R001A060.skeleton, there is one subject initially whose tracking ID is "72057594037930227". When I jump to line 1000, I can see skeleton coordinates for two subjects, whose tracking IDs are "72057594037930243" and "72057594037930244". 

What does this mean?
Are there three subjects in the video or the tracking was stopped in between and started again, giving the subjects new tracking IDs?
If the latter is the case, which new ID corresponds to the subject who was there initially in the video?

Please help me out with this as it is becoming difficult to choose the subject who is to be considered for the action if I can't figure out the corresponding subjects for each set of coordinates.

**Comment by TheSOMGuy** [comment]
Well, that is a good question.
As far as i know i can only say: no, the ID isn't always constant.
We stumbled about the problem that the number of subjects is changing in some skeleton files so this leads to the assumption that the skeleton IDs are also able to change until runtime. 

As a solution for the question which one is the primary skeleton of the set we build a small algorithm which computes the distance of all neurons of one skeleton between two frames. We do this for the whole set and the subject with the highest distance over all frames is at least the primary subject. ( As mentioned in the FAQ section of the dataset. )

> How did you choose the main actor in the preprocessing step?
> We used a heuristic. It's very simple (but not necessarily correct for all the samples). Consider the 
> variance of the X, Y, and Z values of all the joints and add them up. We took the body with the higher 
> value as the main subject.

This also solves the problem with chairs, tables and stuff who are part of some sets.

`	# Compute the absolute amount of movement between two frames over all joints
	def ftf_joint_diff( self, _another_frame_ ):

		# Get the joints from the frames
		_own_joints_ = self.get_ListOfJoints()
		_another_joints_ = _another_frame_.get_ListOfJoints();

		# Create buckets for the world joint position
		_own_world_ = (0,0,0)
		_another_world_ = (0,0,0)

		# This is the bucket for the absolut distance over all joints
		_ive_come_a_long_way_baby_ = 0.0

		for k in range(0, self.get_NumberOfJoints() ):

			# Get the world coordinates of each joint 
			_own_world_ = np.array(_own_joints_[k].get_WorldJoint())
			_another_world_ = np.array(_another_joints_[k].get_WorldJoint())
			
			# Compute the euclidean using numpy
			_ive_come_a_long_way_baby_ += np.linalg.norm( _own_world_ - _another_world_ )

		# Return the shizzle
		return _ive_come_a_long_way_baby_`

The code above takes the joints of the previous frame of one subject and computes the euclidean distance between them and their position in the actual frame. It's not the very best solution ( remember the changing number of skeletons in some skeleton files ) but it works mostly.

**Comment by dracarys983** [comment]
Thanks a lot for your clarification and code.
The issue of not knowing which ID belongs to which skeleton number might still be a problem though.

Anyway, this solution works for now. Closing the issue.
