### ISSUE TITLE
Download NTURGB-D from the google colab

### ISSUE THREAD

**Issue by alirezadizaji** [shahroudy/NTURGB-D#69]
Hi,
I was trying to download both datasets from google colaboratory using the command `!gdown "<drive-id>&confirm=t"`, though I am getting the following error:
```
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser
```
It would be great to be able to download both datasets directly from the google colab. Thanks

**Comment by alirezadizaji** [comment]
Sorry, I should make this issue to the ROSE lab :).

**Comment by junliu021** [comment]
You can download the skeleton data here:
https://drive.google.com/open?id=1CUZnBtYwifVXS21yVg62T-vrPVayso5H
https://drive.google.com/open?id=1tEbuaEqMxAV7dNc4fqu1O4M7mC6CJ50w

For RGB videos, you can only download it on ROSE website.
