### ISSUE TITLE
RGB and depth images processing for CNN

### ISSUE THREAD

**Issue by zhaiyuan** [shahroudy/NTURGB-D#7]
Hi, shahroudy, I want to know how to set the average RGB value when processing the training data before input to a network. And how to set training data and testing data. Thank you and look forward your reply.

**Comment by shahroudy** [comment]
Finding the average RGB value is subjective.
You can sample thousands of frames randomly and calculate an estimated average.
The definition of the train/test splits are clearly provided in the paper (for the two evaluation scenarios).
Please refer the the CVPR paper for more info.
