### ISSUE TITLE
skeleton data is 0 in some frames ,should I delete it ?

### ISSUE THREAD

**Issue by guiyuliu** [shahroudy/NTURGB-D#9]

**Comment by guiyuliu** [comment]
when I use matlab to read the skeleton data frame by frame ,I found in some frames ,skeleton is just 0, for example ,S014C002P007R001A002.skeleton
the first ten frames has no skeleton data at all ,should I delete it ?

**Comment by TheSOMGuy** [comment]
It depends on what do you want to do with the dataset.

I have precomputed the whole dataset and there are three different problems:

1. You have skeleton sequences where the number of skeletons in the file change from 2 to 1.
2. You have skeleton sequences with "NaN" entries.  
3. You have skeleton sequences with zero lines ( all entries of a line are zero, mostly Occlusions ).

So it strongly depend on what do you want to do with the data.
For 1 this means i take a closer look if the main skeleton in the file is there until the end of the sequence. If so, use the sequence. If not, skip it.
For 2 and 3 this means: i skip all the ( incomplete ) data. ( i have a list with all sequences with incomplete or missing data ).

**Comment by Naman-ntc** [comment]
> 1. You have skeleton sequences where the number of skeletons in the file change from 2 to 1.
> 2. You have skeleton sequences with "NaN" entries.
> 3. You have skeleton sequences with zero lines ( all entries of a line are zero, mostly Occlusions ).

4. Sometimes there are more than 2 skeletons instead of 2
